language: php

php:
  - 7.1

before_script:
  - cp .env.travis .env
  - mysql -e 'create database starterkit;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
  - ls -la

notifications:
  slack:
    on_success: never
    on_fail: always